# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J.SocialLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for J.SocialLogin

  pod 'GoogleSignIn'
  target 'J.SocialLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'J.SocialLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
